import { describe, expect, it } from 'vitest';
import { isValidUPS } from './ups.js';

// Vectors generated by the exact algorithm under test (see DECISIONS.md —
// UPS publishes no official checksum spec, so this validates internal
// self-consistency: valid numbers verify, and a single flipped digit fails).
describe('isValidUPS', () => {
  it.each([
    '1Z999AA10123456780',
    '1Z1A2B3C4D5E6F7G82',
    '1ZABCDEF0123456784',
  ])('accepts a valid UPS number: %s', (tn) => {
    expect(isValidUPS(tn)).toEqual({ valid: true, weak: false });
  });

  it('rejects when the check digit is flipped', () => {
    const valid = '1Z999AA10123456780';
    const flipped = valid.slice(0, -1) + '1';
    expect(isValidUPS(flipped).valid).toBe(false);
  });

  it('rejects when an interior digit is flipped', () => {
    // flip the '9' at index 4 to '8'
    const valid = '1Z999AA10123456780';
    const flipped = valid.slice(0, 4) + '8' + valid.slice(5);
    expect(isValidUPS(flipped).valid).toBe(false);
  });

  it('rejects wrong length', () => {
    expect(isValidUPS('1Z999AA1012345678').valid).toBe(false);
  });

  it('rejects missing 1Z prefix', () => {
    expect(isValidUPS('999AA10123456780AB').valid).toBe(false);
  });
});
