import { describe, expect, it } from 'vitest';
import { isValidUSPS, hasAmbiguousUspsPrefix } from './usps.js';

// Vectors generated by the exact algorithm under test.
const VALID_20 = '70123456789012345674'; // 20 digits, non-ambiguous prefix
const VALID_22_92 = '9200111899223197428499'; // 22 digits, ambiguous "92" prefix
const VALID_22_94 = '9400111899223197428497'; // 22 digits, ambiguous "94" prefix

describe('isValidUSPS', () => {
  it('accepts a valid 20-digit number', () => {
    expect(VALID_20).toHaveLength(20);
    expect(isValidUSPS(VALID_20)).toEqual({ valid: true, weak: false });
  });

  it('accepts valid 22-digit numbers', () => {
    expect(isValidUSPS(VALID_22_92).valid).toBe(true);
    expect(isValidUSPS(VALID_22_94).valid).toBe(true);
  });

  it('rejects when the check digit is flipped', () => {
    const lastDigit = VALID_20.slice(-1);
    const flippedLast = lastDigit === '9' ? '8' : '9';
    const flipped = VALID_20.slice(0, -1) + flippedLast;
    expect(isValidUSPS(flipped).valid).toBe(false);
  });

  it('rejects when an interior digit is flipped', () => {
    const flipped = VALID_22_92.slice(0, 5) + (VALID_22_92[5] === '1' ? '2' : '1') + VALID_22_92.slice(6);
    expect(isValidUSPS(flipped).valid).toBe(false);
  });

  it('rejects wrong length (21 digits)', () => {
    expect(isValidUSPS(VALID_22_92.slice(0, 21)).valid).toBe(false);
  });

  it('rejects non-numeric characters', () => {
    expect(isValidUSPS('A' + VALID_20.slice(1)).valid).toBe(false);
  });
});

describe('hasAmbiguousUspsPrefix', () => {
  it('flags 92/93/94/95 prefixed numbers as ambiguous', () => {
    expect(hasAmbiguousUspsPrefix(VALID_22_92)).toBe(true);
    expect(hasAmbiguousUspsPrefix(VALID_22_94)).toBe(true);
  });

  it('does not flag other prefixes', () => {
    expect(hasAmbiguousUspsPrefix(VALID_20)).toBe(false);
  });
});
